### PR TITLE
fix: ensure that invalid scale is not passed to moveTo

### LINKED ISSUE #12: bad rendering and network.body.view.translation is {x:NaN, y:NaN}
Hi

There is a hard-to-reproduce bug with vis network 4.21.0 : sometimes, the networks is not rendered properly (only edges), and it is related to network.body.view.translation being {x:NaN, y:NaN}.

I'm getting the issue on all kind of browser and on different computers, especially the slower one. Maybe the browser is trying to render before the network has been initialized ?

I've found I can reset the view translation to x:0,y:0, then redraw().

Is this bug solved in the 5.0 ?

Regards

### PR DESCRIPTION
**Pull request by Thomaash**
Coerce to number and throw if it isn't grater than zero.

Fixes #12.

All MWE from the issue either work correctly or throw right away.

### CODE REVIEW

File: lib/network/modules/View.js [hunk 1]
```diff
@@ -138,6 +138,13 @@ class View {
       options = {};
       return;
     }
+
+    // Coerce and verify that the scale is valid.
+    options.scale = +options.scale
+    if (!(options.scale > 0)) {
+      throw new TypeError('Scale has to be a number bigger than zero.')
```
Comment (mojoaxel) [inline lib/network/modules/View.js]: How about? `'scale' has to be a number bigger than zero.`

Comment (Thomaash) [reply lib/network/modules/View.js]: Probably a bit more explicit. Will do.
